version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
 
  duelscape.database:
    image: postgres:latest
    container_name: duelscape.database
    environment:
      - POSTGRES_DB=duelscape
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/duelscape-db:/var/lib/postgresql/data
    ports:
      - 5432:5432  
